# Screen Settings 
OF_SCREEN_H=2460
OF_STATUS_H=100
OF_STATUS_INDENT_LEFT=50
OF_STATUS_INDENT_RIGHT=48
OF_HIDE_NOTCH=1
OF_ALLOW_DISABLE_NAVBAR=0
OF_USE_GREEN_LED=0
OF_QUICK_BACKUP_LIST="/boot;/data;"
OF_ENABLE_LPTOOLS=1
OF_NO_TREBLE_COMPATIBILITY_CHECK=1
OF_ENABLE_LPTOOLS := 1
OF_OPTIONS_LIST_NUM := 9
OF_WIPE_METADATA_AFTER_DATAFORMAT=1
OF_ENABLE_FRP_ADDON := 1
OF_USE_DMCTL := 1
OF_FORCE_CASEFOLDING := 1

ifeq ($(FOX_BUILD_TYPE),Stable)
  OF_DONT_KEEP_LOG_HISTORY := 1
endif

